language: c
os:
- osx
- linux
env:
  global:
  - secure: WyWYFgwTedDHQ9OlLVk+996ehZXsD2KBPqFdHz9IgPBBn00x5Z8R7np4OegFYshy5/2ptOIN6Ejjq2352ZpLOUBPV6R0513419rLhbFv3FayZ7b+IAngTLiQu6t2WGYNmOKEZhBdzrHA1YCujI+WSvqcC+6XArAXjIBDCQ36ZluC7shULr2+0DDb9ZA8cXr8Xcd9FitaD4XxTUh+sFRboaJ/nqduZaOSUNRRkwA8gXdKfK7DAt2VZQ9WkTIc3Cq1SNLVFPhTsKos5YbILa4KsRNPPwENXYdiv2h+S7ER70y6fD6VzGjvh1kdEzxnba5xNJhDtntDM7RG+LzTAcW90x4lg4TAgjFLCCBVFfbkL0iVQbHnsSmpi+IKWi83jYzjGzBtBndMpq+Qm317uy76f+hQFGcmEuVSwKN7YraXXpzu31p6j8UYhnQNYQAimaBYGH02Q7AyeqfgrnyUY7N0POme06LQ3E0PXozxTXO/vTcwu51JnBNkIaHDY+h80lLQOm8yBbhNtmbiWkpM3aEaUbDYUrph7hIXpt/SURYFZBZaYVXj5nFTF/T3JZ/kTPvWV5iuRBRqcNCcoCYjTSGTG4KrcoTPT1lzAMJX4V/8rfOIP2NGds0kas15DtUPrdcTdCl9JfLSoPEAGPQ85Oxm7qFSQqzhx/IJcGXvOTBWjrI=
  - secure: OIhs8592+GYRTCzpvEViCADBwho7DugOrsIUwXaPlrGWdwEarRcISyv0e+4pe92FeSvLfDrDS6UbnVN7pWxL/OkMW9WZEdceO55uCws7v5jB8jx1x3L2Agrv0wtsTDRok5vf5zJkZdjFUg0A/7sFy82X6Gqsofor2o1XM9zU5neVvxZCefwa95yCOlAwhkBDNASHmqBqr+4JoizaFjDvzYDB5nSlfr9toUMD0LcZzMUhTj3b+OD/Cox4A9NFbkrYdSnRViwJ+SwP4qu7gZkVV0A+EmIM7CnhQEpGlOFb9FhjSqzr2alJHivfD6Ayc2wAh0HXmrzvbAdGu/zvOcJGP+LuqY1FdNSZ3rAl4A9HlyckbscSyUHK16EXUVlM8/0k9vGnqHZXXsiy8UktCa0U/8KxKcIqxaW2iVYBIph0BNMY9rzGfzRZo1J97LXC0eCjZEipUbWEd1O4J349d0B8AhlyfZh+tijbIhvoyJQk7JVLyyQMZWGx/99NHjLnLxNvLgEXfGDBHIlNos+N7RsVV4nBFslNhSzeMEKwKCrwgy9Ryw+NOKdwh95ZQrHhrSwUAwp1vTB7Lx/z3grdGwu+1gILq2nfSxqK9wkolo3HWPVcSEhnX0mej7MB//V0vKONDNjuqHi8Ya0HVk2zdD+KUQ+rJbSa6+SKjrljDiGi/p0=
  - secure: GZfv/b8LUSnET8wU2uYDjfZcrn6X9E2xP43UW0kYRtQI/L8RKcZNfkNpmjDrNbw9x6+34BMydB7SM2rIBsnsQTW5OVziBtA1Qo0Iq48oruO9LQRE7AHjLoNF74ECr+8f2LL86P0iyFGbS2ZY6tuJvMpNVphZuPz6pTOWGUp91bp9zR82rQCRq8txTAE2Yc4mSIoUzxeSNLWuf/2TunmZlWSOKqAQfOemh5Zm2+atOJJ9u6MqGb5GkyYFAh3cfywHXT/eS9BABGdSGaH9MtH8g/al1VRe0h2JnC+E4DviiKHKse9Opb4i3+Yye9QKVlFEzviZNcK0ocN/ZQ3jATzQJiV1NDuBfcylSiXk13GqX2PE7+3nxuAt8LXoSnbcvEOjsCr4wqKy8ooeqyXEriy7OI3MOy2GksXg4g9+yC2Znw7YI2Bfk6sdpmQqWOkpI41VkI+AdByQFw34IPtLnPZS+h+xLH2WH6JviLTxoJUeY6yCWpt6gWj7AZ+ENMTFNPPdcF4ASIJTnTmnZ7lhIJrzVJVsWpoM9oTemeEF5lqR7iBdJBZkewiKoFrADUp3smUQjn2DL4P0WYIt/rkFutrjp2229ywRcAQYNlh7zeBmUAH842iIx8Mk/b11Nzn+16+UFzryQ92qaVbFa7SdqGYJQ5gGCNrGDlNecb0XpB5d+aA=
  matrix:
  - NODE_VERSION="4.2.4"
addons:
  apt:
    packages:
    - libudev-dev
install:
- export PATH=./node_modules/.bin/:$PATH
script:
- npm install --build-from-source --node-gyp=$(which pangyp)
- "./node_modules/.bin/node-pre-gyp package"
- "./node_modules/.bin/node-pre-gyp-github publish --release"
