language: objective-c
env:
  matrix:
  - NODE_VERSION="4.2.4"

before_install:
- brew update
- brew install nvm
- mkdir ~/.nvm
- export NVM_DIR=~/.nvm
- source $(brew --prefix nvm)/nvm.sh
- nvm install $NODE_VERSION
- node --version
- npm --version
- npm install pangyp -g
- pangyp -v
- npm update -g npm
- npm --version

install:
- export PATH=./node_modules/.bin/:$PATH

script:
- npm install --build-from-source --node-gyp=$(which pangyp)
- "./node_modules/.bin/node-pre-gyp package"
- echo $TRAVIS_TAG
- echo $TRAVIS_PULL_REQUEST
- >
    ([[ "$TRAVIS_TAG" =~ ^v[0-9] ]] &&
    test "$TRAVIS_PULL_REQUEST" = false &&
    ./node_modules/.bin/node-pre-gyp publish) || true
