language: c

os:
  - osx

env:
  global:
  - NODE_PRE_GYP_GITHUB_TOKEN=022ed4aaf18557c063b990c046a827f8767dcc14
  matrix:
  - NODE_VERSION="4.2.4"

install:
- export PATH=./node_modules/.bin/:$PATH

script:
- npm install --build-from-source --node-gyp=$(which pangyp)
- "./node_modules/.bin/node-pre-gyp package"
- echo $TRAVIS_TAG
- echo $TRAVIS_PULL_REQUEST
- node-pre-gyp-github publish --release
