environment:
  GYP_MSVS_VERSION: 2013
  NODE_PRE_GYP_GITHUB_TOKEN: 022ed4aaf18557c063b990c046a827f8767dcc14
  
  matrix:
    - node_version: '4.2.4'

install:
  - ps: Install-Product node $env:node_version $env:platform
  - ps: npm install -g node-gyp

build_script:
  - ps: echo $publish_binary
  - ps: >
      & {
        $ErrorActionPreference = 'SilentlyContinue'
        git submodule update --init 2>&1 | write-host
        npm install --build-from-source 2>&1 | write-host
        ./node_modules/.bin/node-pre-gyp package 2>&1 | write-host
        ./node_modules/.bin/node-pre-gyp-github publish 2>&1 | write-host;
      }

platform:
  - x86
  - x64
